name: our_music
description: 'Projeto flutter para estudos'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg:
  flutter_bloc:
  hydrated_bloc:
  path_provider:
  firebase_core:
  firebase_auth:
  get_it:
  flutter_dotenv:

  dartz:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  change_app_package_name:
  rename_app:
  flutter_launcher_icons:

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/images/icons/
    - assets/fonts/
    - assets/vectors/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.ttf
          weight: 900
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 600
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-Regular.ttf
          weight: 400
        - asset: assets/fonts/Satoshi-Light.ttf
          weight: 300

flutter_launcher_icons:
  android: 'launcher_icon'
  adaptive_icon_background: '#FF8216'
  adaptive_icon_foreground: 'assets/images/icons/ic_launcher_foreground.png'
  adaptive_icon_round: 'assets/images/icons/ic_launcher_round.png'
  image_path: 'assets/images/icons/ic_launcher.png'
