// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcwi3b0uyAI8sKqsbn9A_a4OdhtULmSoI',
    appId: '1:384205474942:web:3f07f8e4c30f4725739c2f',
    messagingSenderId: '384205474942',
    projectId: 'our-music90123',
    authDomain: 'our-music90123.firebaseapp.com',
    storageBucket: 'our-music90123.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCQvUgYkNEWNQTgAZ9NpTLc8DyU310pQc',
    appId: '1:384205474942:android:aae404327be4b6da739c2f',
    messagingSenderId: '384205474942',
    projectId: 'our-music90123',
    storageBucket: 'our-music90123.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcwi3b0uyAI8sKqsbn9A_a4OdhtULmSoI',
    appId: '1:384205474942:web:35eb39419be31b8d739c2f',
    messagingSenderId: '384205474942',
    projectId: 'our-music90123',
    authDomain: 'our-music90123.firebaseapp.com',
    storageBucket: 'our-music90123.appspot.com',
  );
}
