// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.get('API_KEY_WEB'),
    appId: dotenv.get('APP_ID_WEB'),
    messagingSenderId: '384205474942',
    projectId: 'our-music90123',
    authDomain: 'our-music90123.firebaseapp.com',
    storageBucket: 'our-music90123.appspot.com',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.get('API_KEY_ANDROID'),
    appId: dotenv.get('APP_ID_ANDROID'),
    messagingSenderId: '384205474942',
    projectId: 'our-music90123',
    storageBucket: 'our-music90123.appspot.com',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.get('API_KEY_WINDOWS'),
    appId: dotenv.get('APP_ID_WINDOWS'),
    messagingSenderId: '384205474942',
    projectId: 'our-music90123',
    authDomain: 'our-music90123.firebaseapp.com',
    storageBucket: 'our-music90123.appspot.com',
  );
}
